version: 2.1

orbs:
  docker: circleci/docker@2.1.1

master_branch_filter: &mbf
  branches:
    only: /^main$/

workflows:
  build_images:
    jobs:
      - docker/publish:
          name: Build RustCI Image
          filters: *mbf
          context:
            - "GitHub PAT"
          image: "emanguy/rust-ci"
          docker-username: CONTAINER_REPO_USERNAME
          docker-password: CONTAINER_REPO_PAT
          dockerfile: ./RustCI.dockerfile
          registry: ghcr.io
          tag: $(source VERSIONS.txt && echo $RustCI_VERSION)
