version: 2.1

orbs:
  docker: circleci/docker@3.0.1

master_branch_filter: &mbf
  branches:
    only: /^main$/

workflows:
  build_images:
    jobs:

      - docker/publish:
          name: Build RustCI Image
          filters: *mbf
          context:
            - "GitHub PAT"
          image: "emanguy/rust-ci"
          before_build:
            - docker/pull:
                ignore_docker_pull_error: true
                images: "ghcr.io/emanguy/rust-ci:$(source VERSIONS.txt && echo $RustCI_VERSION)"
          docker_username: CONTAINER_REPO_USERNAME
          docker_password: CONTAINER_REPO_PAT
          dockerfile: ./RustCI.dockerfile
          registry: ghcr.io
          tag: $(source VERSIONS.txt && echo $RustCI_VERSION)

      - docker/publish:
          name: Build Caddy Image
          filters: *mbf
          context:
            - "GitHub PAT"
          image: "emanguy/caddy-domainnameshop"
          before_build:
            - docker/pull:
                ignore_docker_pull_error: true
                images: "ghcr.io/emanguy/caddy-domainnameshop:$(source VERSIONS.txt && echo $CaddyDNS_VERSION)"
          docker_username: CONTAINER_REPO_USERNAME
          docker_password: CONTAINER_REPO_PAT
          dockerfile: ./CaddyDomainNameShop.dockerfile
          registry: ghcr.io
          tag: $(source VERSIONS.txt && echo $CaddyDNS_VERSION)
